version: '3.1'

services:
  db:
    container_name: duogg_db
    image: postgres
    restart: on-failure
    ports:
      - 5433:5432
    volumes:
      - .docker/volumes/db:/var/lib/postgres
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: root1234

  adminer:
    container_name: duogg_adminer
    image: adminer
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
