name: CI Run Migrations

on: [pull_request]

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_ROOT_PASSWORD: root1234
        ports:
          - '5433:5432'

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: false
          scope: dale-gg

      - name: Installation
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Conf ENV
        run: sh -c "ls -a && cp .env.example .env"

      - name: Try Linting
        run: yarn lint:fix

      - name: Run migrations
        run: yarn migrate
        env:
          CI: true
